# Generated by Django 2.1.5 on 2019-10-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_article_summer_note_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='summer_note_model',
            name='attachment_ptr',
        ),
        migrations.DeleteModel(
            name='summer_note_model',
        ),
    ]
