# Generated by Django 2.1.5 on 2019-10-31 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_summernote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summernote',
            name='attachment_ptr',
        ),
        migrations.DeleteModel(
            name='SummerNote',
        ),
    ]
