# Generated by Django 2.1.5 on 2019-11-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_uploadfilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFileModel',
        ),
    ]
