# Generated by Django 2.1.5 on 2019-11-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20191106_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='imagetest',
            name='photo',
        ),
        migrations.AddField(
            model_name='imagetest',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='imagetest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='imagetest',
            name='filtered_image',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d/filtered'),
        ),
        migrations.AddField(
            model_name='imagetest',
            name='image',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d/orig'),
        ),
    ]
